### ISSUE TITLE
libgilzoide-sqlite-net.so not 16KB-aligned on Android 15+ (ARM64)

### ISSUE THREAD

**Issue by MustafaBey654** [gilzoide/unity-sqlite-net#71]
Unity version 6.0 (6000.0.47f1)

Plugin 'Assets/Plugins/lib/android/arm64/libgilzoide-sqlite-net.so' is not 16KB-aligned. This may cause issues on ARM64 devices running Android 15+.
More info: <a href="https://developer.android.com/guide/practices/page-sizes">https://developer.android.com/guide/practices/page-sizes</a>.
System.Linq.Enumerable/WhereEnumerableIterator`1<object>:MoveNext ()
Bee.BeeDriver.BeeDriver:WriteDataForBuildProgram (Bee.BeeDriver.InternalState,System.Threading.Tasks.TaskCompletionSource`1<int>)
Bee.BeeDriver.BeeDriver/<>c__DisplayClass0_0:<BuildAsync>g__WriteData|0 ()
Bee.BeeDriver.BeeDriver:BuildAsync (Bee.BeeDriver.BuildRequest,System.Threading.CancellationToken)
UnityEditor.EditorApplication:Internal_CallDelayFunctions ()

I tried to make changes via wsl but I did not succeed. It causes problems on Android 15 and above devices, I built it on both Unity and the Redmi 12 Pro device and encountered the same problem.

**Comment by gilzoide** [comment]
Hey @MustafaBey654 , thanks for the report. This was supposedly fixed by #64 and should be available in version 1.2.3.
Which version of this package are you using?

**Comment by gilzoide** [comment]
Just ran [check_elf_alignment.sh](https://cs.android.com/android/platform/superproject/main/+/main:system/extras/tools/check_elf_alignment.sh) in the ARM64 lib from tag 1.2.4 and it seems to be properly aligned.

<img width="692" alt="Image" src="https://github.com/user-attachments/assets/fc67ea3f-75c5-4dc0-8ebd-c8185fdd70d2" />

**Comment by gilzoide** [comment]
Well, so you should have an aligned DLL already 🤔
Say, what's that stacktrace you posted in the issue? Is it from the build process? Or is it a log from the client?

**Comment by MustafaBey654** [comment]
Hello  @gilzoide,

Thank you for your previous replies. I have thoroughly followed your suggestions and performed extensive troubleshooting on my end to ensure there are no caching or setup issues.

I used WSL (Windows Subsystem for Linux) to directly inspect the libgilzoide-sqlite-net.so file that Unity is using in my project, located at:
/mnt/d/Unity/PlayStoreGames/DuaUygulamasi/Library/PackageCache/com.gilzoide.sqlite-net@cf7ea3756d7b/Plugins/lib/android/arm64/libgilzoide-sqlite-net.so

As check_elf_alignment.sh is not included in the Unity package, I used the standard Linux tool readelf -S to check the section alignments of the .so file.

Here is the output from readelf -S filtered for relevant sections: 
[10] .rodata           PROGBITS         000000000000dfb0  0000dfb0
[13] .text             PROGBITS         00000000000433c8  0003f3c8
[15] .data.rel.ro      PROGBITS         0000000000189200  00181200
[20] .data             PROGBITS         000000000018f868  00183868
[21] .bss              NOBITS           0000000000193250  00187248

Based on this output, the start addresses of the .rodata, .text, .data.rel.ro, .data, and .bss sections are not aligned to 16KB (0x4000) boundaries. For instance, the .text section starts at 0x433c8 and .rodata at 0xdfb0, neither of which is a multiple of 0x4000.

This directly confirms Unity's warning:
Plugin 'Packages/com.gilzoide.sqlite-net/Plugins/lib/android/arm64/libgilzoide-sqlite-net.so' is not 16KB-aligned. This may cause issues on ARM64 devices running Android 15+.

It seems that the libgilzoide-sqlite-net.so file included in version 1.2.4 (installed via https://github.com/gilzoide/unity-sqlite-net.git#1.2.4) is indeed not 16KB-aligned, despite the previous fixes mentioned.

Could you please investigate this further from your side to ensure the .so files are correctly built with 16KB alignment for Android 15+ compatibility?

Thank you for your time and effort.

**Comment by MustafaBey654** [comment]
Hi @gilzoide,
Regarding your question about testing on a 16KB page size device:

I built an APK and tested it on my Redmi Note 12 Pro (Snapdragon 732G) running Android 13. Surprisingly, the app seems to run fine without any crashes or obvious issues on this device.

However, as my device is currently on Android 13, it does not use the 16KB page size that Android 15+ will require. My readelf output, Unity's warning, and Android Studio's APK analyzer still confirm that the libgilzoide-sqlite-net.so library is not 16KB-aligned for ARM64.

Additionally, I am also receiving a warning about this exact issue in the Google Play Console when uploading the APK. This confirms that the problem is recognized by Google's distribution platform as well, indicating potential compatibility issues for future devices.

This suggests that the issue might only manifest on devices running Android 15 and newer versions which adopt the 16KB page size requirement.

I hope this information is helpful for your investigation.

Thanks!

**Comment by gilzoide** [comment]
Hey @MustafaBey654.

> I was wondering if there has been any progress on this matter since our last communication about a week ago.

Not on my side. Unfortunately I have too many personal projects and not enough time to handle all issues and development of all of them.

> I'm closely monitoring this, especially given the readelf -S outputs showing misalignment and the warnings I'm receiving from the Google Play Console.

Actually, the [documentation](https://developer.android.com/guide/practices/page-sizes#elf-alignment) only says that the LOAD segments should be aligned to 16kb, the [check_elf_alignment.sh](https://cs.android.com/android/platform/superproject/main/+/main:system/extras/tools/check_elf_alignment.sh) script linked in the docs confirms the library is properly aligned, [I already sent you a screenshot of its output](https://github.com/gilzoide/unity-sqlite-net/issues/71#issuecomment-2916042348).

To build this package, I'm following the docs on [how to build with 16kb page size support](https://developer.android.com/guide/practices/page-sizes#other-build-systems). Provided that the Gradle scripts are also compatible, the APK should work. Well, it does actually work, I have tested it in the Android emulator!

I really don't know why Android Studio and Google Play are flaging the library and built APKs as not aligned, since the build just works in devices using 16kb page sizes. Maybe it's a false positive on Google's side 🤷 If it works in the devices, there shouldn't be too much to worry about.

> I've tested the app on a real device, an OPPO A3, which is running ColorOS 15.0 (Android 15). The device uses a Qualcomm Snapdragon 6s Gen1 processor, confirming it's an ARM64 device.

You know, not all devices running Android 15 on ARM64 are configured to use 16kb page sizes at the system level. Did you setup your device to use 16kb page sizes?

> Any further insights or progress on properly aligning the library for Android 15+ devices would be greatly appreciated as I'm waiting for a stable solution to continue adding new features to my project.

I'm not actively looking into this, but I will have to at some point at work (I do work with mobile Unity games in my day job). I'll let you know if I find anything. By the way, I'd also appreciate any new information about this as well, if you ever have any.

<hr/>

Apart from that, it's super easy to ditch the shared libraries and let Unity compile SQLite directly on IL2CPP-enabled builds. That's what iOS and Web builds do. I make native builds for Android because someone might be using the Mono script backend.

**Comment by MustafaBey654** [comment]
Hello, I am using this version as NDK in my Unity 6000.0.47f1 version. Pkg.Desc = Android NDK
Pkg.Revision = 27.2.12479018
Pkg.BaseRevision = 27.2.12479018
Pkg.ReleaseName = r27c

**Comment by gilzoide** [comment]
Hi @MustafaBey654. I understand your concern. To be honest, for me the fact that builds with this package work in the 16kb device (even in the emulator) and the fact that empty Unity builds are marked in Android Studio Narwhal preview as not supporting them is enough to figure out the problem is not in this package itself. Could be in Unity's side, could be in Google's / Android Studio's side, I don't know.

I just pushed a new branch [android-build-from-source](https://github.com/gilzoide/unity-sqlite-net/tree/android-build-from-source) where the native code is not prebuilt anymore, but rather built from source by Unity (requires IL2CPP). You can install this branch via UPM using the following URL:
```
https://github.com/gilzoide/unity-sqlite-net.git#android-build-from-source
```
This way, Unity is the one controlling how the native build is done, so it uses the exact same NDK and build flags and etcetera that Unity uses. You won't get these warnings anymore because there will not be any prebuilt libraries to warn about, giving you peace of mind. How does that sound to you?

**Comment by SamiKuhakoskiGGB** [comment]
libgilzoide-sqlite-net.so is 16KB aligned, but the meta file libgilzoide-sqlite-net.so.meta isn't up to date in the package, so Unity still shows the warning.

**Comment by MustafaBey654** [comment]
Hello, I solved the Arm64 16 KB issue with the update you provided. I installed my app on the Play Console. The problem no longer appears. I'm very sorry for the late reply. I don't have time to work. The version I'm using is Unity 6 6000.0.47f1.

**Comment by SamiKuhakoskiGGB** [comment]
> > libgilzoide-sqlite-net.so is 16KB aligned, but the meta file libgilzoide-sqlite-net.so.meta isn't up to date in the package, so Unity still shows the warning.
> 
> [@SamiKuhakoskiGGB](https://github.com/SamiKuhakoskiGGB) how could we update this .meta file? What is missing in it? I mean, Unity hasn't done anything automatically, I'm not aware of what should be done.

It's a Unity bug, that it doesn't update the Meta file. This can be done manually by selecting the .so file and selecting reset from the 3 dot menu in inspector. But the reset cannot be done to files inside package installed by unity package manager, so the updated/reseted .meta needs to be in the package it self.

**Comment by gilzoide** [comment]
Fix released in version 1.3.2

Cheers \o/
